Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -1,10 +1,7 @@
 name: Metrics
 on:
-  # Schedule daily updates
   schedule: [{cron: "0 0 * * *"}]
-  # (optional) Run workflow manually
   workflow_dispatch:
-  # (optional) Run workflow when pushing on master/main
   push: {branches: ["main"]}
 jobs:
   github-metrics:
@@ -14,6 +11,19 @@ jobs:
     permissions:
       contents: write
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Copy action.yml to root
+        run: cp .github/workflows/action.yml action.yml
+
+      - name: Verify action file existence
+        run: |
+          if [ ! -f action.yml ] && [ ! -f action.yaml ] && [ ! -f Dockerfile ]; then
+            echo "Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile'."
+            exit 1
+          fi
+
       - uses: kinho6119/kinho6119@main
         with:
           token: ${{ secrets.METRICS_TOKEN }}
